Usuario/routes.py
from flask import Blueprint, render_template, redirect,url_for,flash
from flask_login import login_user,logout_user,login_required,current_user
from datetime import datetime, timedelta
from authentication import auth
from sqlalchemy.exc import SQLAlchemyError
from app import db
import models as model
import Usuario.forms as formulario
import Usuario.functions.f_perfil as fper
import Usuario.functions.f_editarPerfil as fedp
import Usuario.functions.f_AccionesUsuario as facu
import Viaje.functions.f_AccionesConductor as vfac

usuario_bp = Blueprint('usuario_bp', __name__, url_prefix='/usuario', template_folder='templates', static_folder='static')


@usuario_bp.route('/registro', methods=['GET', 'POST'])
def Registro():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))
    
    form = formulario.RegistroUsuario()

    if form.validate_on_submit():

        nombre= form.nombreUsuario.data
        apellido = form.apellidoUsuario.data
        email = form.email.data.strip()
        telefono = form.telefono.data
        fecha_nacimiento = form.fecha_nacimiento.data
        passw = form.password.data

        usuario_email = model.Usuario.find_by_email(email)
        usuario_telefono = model.Usuario.find_by_telefono(telefono)

        if usuario_email:
            flash("El email especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        elif usuario_telefono:
            flash("El número de teléfono especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        else:
            try:
                nuevoUsuario_firebase = auth.create_user_with_email_and_password(email, passw)
                nuevoUsuario = model.Usuario(
                    nombre=nombre,
                    apellido=apellido,
                    email=email,
                    contrasenia=nuevoUsuario_firebase['idToken'],
                    telefono=telefono,
                    fecha_nacimiento=fecha_nacimiento,
                    fecha_actualizacion=datetime.now(),
                    fecha_creacion= datetime.now(),
                    id_tipo_usuario=1,
                    id_estado_usuario=1
                )
                model.Usuario.save_to_db(nuevoUsuario)
                if model.Usuario.query.get(nuevoUsuario.id):
                    flash("Usuario creado exitosamente, complete sus credenciales para ingresar.")
                    return redirect(url_for('usuario_bp.Login'))
                else:
                    auth.delete_user_account(nuevoUsuario_firebase['idToken'])
                    flash("Hubo un error al crear la cuenta, vuelve a intentarlo más tarde.")
                    return redirect(url_for('usuario_bp.Registro'))
            except:
                flash('Hubo un error con tu cuenta, revisa nuevamente los datos ingresados.')
                return redirect(url_for('usuario_bp.Registro'))
    return render_template('registro.html', form=form)

@usuario_bp.route('/login', methods=['GET', 'POST'])
def Login():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.Login()

    if form.validate_on_submit():

        passw = form.contrasenia.data
        email = form.nombreUsuario.data.strip()
        
        try:
            usuario = model.Usuario.find_by_email(email)

            if usuario:
                inicio = auth.sign_in_with_email_and_password(email, passw)
                if inicio:
                    login_user(usuario)
                    return redirect(url_for('viaje_bp.BuscarViaje'))
                else: 
                    flash("La contraseña ingresada es incorrecta")
                    return redirect(url_for('usuario_bp.Login'))
        except:
            print("exception")
            flash("El usuario ingresado es incorrecto")
            return redirect(url_for('usuario_bp.Login'))
    return render_template('login.html', form=form)

@usuario_bp.route('/reset/contrasenia', methods=['GET', 'POST'])
def ResetearContrasenia():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.ReseteoContrasenia()

    if form.validate_on_submit():
        email = form.emailUsuario.data.strip()
        try:
            auth.send_password_reset_email(email)
            flash('Te enviamos un email a la cuenta de correo para que puedas resetear tu contraseña.')
            return redirect(url_for('usuario_bp.Login'))
        except:
            flash('El correo ingresado no pertenece a una cuenta existente.')
            return redirect(url_for('usuario_bp.ResetearContrasenia'))
    return render_template('reseteoContrasenia.html', form=form)

@usuario_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def Logout():
    logout_user()
    return redirect(url_for('usuario_bp.Login'))


@usuario_bp.route('/perfil', methods=['GET', 'POST'])
@login_required
def Perfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)

@usuario_bp.route('/perfil/<idUsuario>', methods=['GET', 'POST'])
@login_required
def PerfilUsuario(idUsuario):

    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)


@usuario_bp.route('/perfil/editar', methods=['GET', 'POST'])
@login_required
def EditarPerfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)
    print(usuario)
    form = formulario.EditarPerfil()
    
    try:
        if form.validate_on_submit():
            telefono = model.Usuario.query.filter(model.Usuario.telefono == form.telefono.data,
                                                  model.Usuario.id != idUsuario).all()
            if telefono:
                flash("El número de teléfono especificado ya esta en uso.")
                return redirect(url_for('usuario_bp.EditarPerfil'))

            fedp.actualizar_usuario_con_formulario(usuario, form)
            db.session.commit()
            flash('Perfil editado con éxito')
            return redirect(url_for('usuario_bp.Perfil'))
        else:
            fedp.cargar_datos_del_usuario_en_formulario(form, usuario)
            return render_template('editar_perfil.html', form=form, usuario = usuario)
    except SQLAlchemyError as e:
        print('Error al editar el perfil:', str(e))
        return redirect(url_for('usuario_bp.EditarPerfil'))
    

@usuario_bp.route('/perfil/eliminar', methods=['GET', 'POST'])
@login_required
def EliminarCuenta():
    return True

Viaje/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, session
import models as model
from flask_login import login_required,current_user
from datetime import datetime, timedelta
from sqlalchemy.exc import SQLAlchemyError
import routes as r
import Viaje.forms as formulario
from app import maps, db

import Viaje.functions.f_EditarViaje as fedv
import Viaje.functions.f_EliminarViaje as felv
import Viaje.functions.f_PublicarViaje as fpuv
import Viaje.functions.f_SolicitudViaje as fsov
import Viaje.functions.f_AccionesConductor as facc
import Viaje.functions.f_BuscarViaje as fbuv
import Viaje.functions.f_IniciarViaje as finv

viaje_bp = Blueprint('viaje_bp', __name__, url_prefix='/viaje', template_folder='templates', static_folder='static')
 


######################    
##### CONDUCTOR ######
######################

@viaje_bp.route('/publicar', methods=['GET', 'POST'])
@login_required
def PublicarViaje():
    try:
        idUsuario = current_user.get_id()
        conductor = model.Conductor.query.filter_by(id_usuario=idUsuario).all()
        form = formulario.NuevoViaje()

        # Obtener vehículos activos directamente desde Conductor
        vehiculos_activos = (
            model.Conductor.query
            .join(model.Vehiculo)
            .filter(
                model.Conductor.id_usuario == idUsuario,
                model.Vehiculo.id_estado_vehiculo == 1
            )
            .all()
        )

        # Asignar las opciones al campo de selección
        form.vehiculo.choices = [(0, "Vehículo")] + [(c.id, c.vehiculo.patente) for c in vehiculos_activos]


        if form.validate_on_submit():
            fecha_inicial = datetime.combine(form.fecha_inicio.data, form.hora_inicio.data)
            if not fpuv.mayorOigualEdad(fecha_inicial):
                flash('Fecha de inicio del viaje errónea.')
                return redirect(url_for('viaje_bp.PublicarViaje'))
            vehiculo, origen, destino, cantidad_asientos, fecha_inicio, hora_inicio, equipaje, mascota, alimentos = fpuv.obtener_datos_del_formulario(form)
            coordenadas_y_distancia = fpuv.obtener_coordenadas_y_distancia(origen, destino)

            if coordenadas_y_distancia:
                latitud_origen, longitud_origen, latitud_destino, longitud_destino, distancia, duracion = coordenadas_y_distancia

                fpuv.guardar_datos_en_la_base_de_datos(
                    vehiculo, origen, destino, cantidad_asientos, fecha_inicio, hora_inicio,
                    latitud_origen, longitud_origen, latitud_destino, longitud_destino, distancia, duracion,
                    equipaje, mascota, alimentos
                )

                flash('Viaje publicado con éxito', 'success')
                return redirect(url_for('viaje_bp.BuscarViaje'))
            else:
                flash('Hubo un error al obtener detalles de ubicación.', 'error')
        else:
            return render_template('publicar_viaje.html', form=form)
    except Exception as e:
        print(f"Se produjo una excepción: {e}")
        flash('No se pudo publicar el viaje. Inténtalo de nuevo más tarde.')
        return render_template('publicar_viaje.html', form=form)

@viaje_bp.route('/editar/<idViaje>', methods=['GET', 'POST'])
@login_required
def EditarViaje(idViaje):
    viaje = model.Viaje.query.get(idViaje)
    
    if not viaje:
        return fedv.redireccionar_y_mostrar_error('Viaje no encontrado', 'error', 'viaje_bp.ViajesPublicados')
    
    if not fedv.tiene_permiso_para_editar(viaje):
        return fedv.redireccionar_y_mostrar_error('No tienes permiso para editar este viaje', 'error', 'viaje_bp.ViajesPublicados')

    form = fedv.inicializar_formulario(viaje)

    try:
        if form.validate_on_submit():
            fedv.actualizar_viaje_con_formulario(viaje, form)
            db.session.commit()
            flash('Viaje editado con éxito', 'success')
            return redirect(url_for('viaje_bp.VerViaje', idViaje=idViaje))
        else:
            fedv.cargar_datos_del_viaje_en_formulario(form, viaje)
            return render_template('editar_viaje.html', form=form, viaje=viaje)
    except SQLAlchemyError as e:
        flash('Error al editar el viaje', 'error')
        print('Error al editar el viaje:', str(e))
        return redirect(url_for('viaje_bp.ViajesPublicados'))

@viaje_bp.route('/eliminar/<idViaje>', methods=['GET', 'POST'])
@login_required
def EliminarViaje(idViaje):
    viaje = model.Viaje.query.get(idViaje)

    if not viaje:
        return fedv.redireccionar_y_mostrar_error('Viaje no encontrado', 'error', 'viaje_bp.BuscarViaje')

    if not felv.tiene_permiso_para_eliminar(viaje):
        return fedv.redireccionar_y_mostrar_error('No tienes permiso para cancelar este viaje', 'error', 'viaje_bp.BuscarViaje')

    felv.eliminar_viaje(viaje)

    return redirect(url_for('viaje_bp.BuscarViaje'))

@viaje_bp.route('/publicados', methods=['GET', 'POST'])
@login_required
def ViajesPublicados():
    try:
        idUsuario = current_user.get_id()
        # Busco viajes publicados por ese usuario, es decir siendo conductor.
        conductores = model.Conductor.query.filter_by(id_usuario=idUsuario).all()

        viajes_por_conductor = []

        for conductor in conductores:
            viajes = model.Viaje.query.filter_by(id_conductor=conductor.id, id_estado_viaje = 3).order_by(model.Viaje.id.desc()).all()
            viajes_por_conductor.extend(viajes)

        if not viajes_por_conductor:
            raise Exception("No se encontraron viajes correspondientes al conductor.")

        return render_template('viajes_publicados.html', viajes=viajes_por_conductor)
    except Exception as e:
        mensaje = "Usted aún no ha publicado ningún viaje."
        return render_template('viajes_publicados.html', mensaje = mensaje)

@viaje_bp.route('/cancelados', methods=['GET', 'POST'])
@login_required
def ViajesCancelados():
    try:
        idUsuario = current_user.get_id()
        # Busco viajes de ese usuario, es decir siendo conductor.
        conductores = model.Conductor.query.filter_by(id_usuario=idUsuario).all()

        viajes_por_conductor = []

        for conductor in conductores:
            viajes = model.Viaje.query.filter_by(id_conductor=conductor.id, id_estado_viaje = 4).all()
            viajes_por_conductor.extend(viajes)

        if not viajes_por_conductor:
            raise Exception("No se encontraron viajes correspondientes al conductor.")

        return render_template('viajes_cancelados.html', viajes=viajes_por_conductor)
    except Exception as e:
        mensaje = "Usted aún no ha cancelado ningún viaje."
        return render_template('viajes_cancelados.html', mensaje = mensaje)

@viaje_bp.route('pasajero/<idPasajero>/confirmar', methods=['GET', 'POST'])
@login_required
def AceptarPasajero(idPasajero):
    if facc.modificar_estado_pasajero(idPasajero, 'Confirmado'):
        pasajero = model.Pasajero.query.get(idPasajero)
        asientosActuales = pasajero.viaje.asientos_disponibles
        pasajero.viaje.asientos_disponibles = asientosActuales - 1
        db.session.commit()
    return redirect(url_for('viaje_bp.VerViaje', idViaje=pasajero.id_viaje))

@viaje_bp.route('pasajero/<idPasajero>/rechazar', methods=['GET', 'POST'])
@login_required
def RechazarPasajero(idPasajero):
    pasajero = model.Pasajero.query.get(idPasajero)
    if facc.modificar_estado_pasajero(idPasajero, 'Rechazado'):
        return redirect(url_for('viaje_bp.VerViaje', idViaje=pasajero.id_viaje))

@viaje_bp.route('/<idViaje>/pasajeros/<idEstado>', methods=['GET', 'POST'])
@login_required
def VerPasajeros(idViaje, idEstado):
    viaje = model.Viaje.query.get(idViaje)
    #Estado 2 = Pendiente
    #Estado 3 = Rechazado
    #Estado 4 = Cancelado
    pasajeros = fsov.pasajeros_viaje(idViaje, idEstado)

    return render_template('pasajeros_viaje.html', pasajeros = pasajeros, viaje = viaje)

@viaje_bp.route('/solicitudes/recibidas', methods=['GET', 'POST'])
@login_required
def SolicitudesRecibidas():
    idUsuario = current_user.get_id()
    viajes_conductor = facc.viajes_pendientes_como_conductor(idUsuario)

    solicitudes = []
        
    for viaje in viajes_conductor:
        pasajero_pendiente = model.Pasajero.query.filter_by(id_viaje = viaje.id, id_estado_pasajero = 2).first()
        if pasajero_pendiente:
            # Agrega el viaje que tiene pasajeros pendientes de confirmación o rechazo
            solicitudes.append(pasajero_pendiente.viaje)
    if solicitudes:     
        return render_template('solicitudes_recibidas.html', solicitudes = solicitudes)
    else:
        mensaje = 'Usted no ha recibido solicitudes'
        return render_template('solicitudes_recibidas.html', mensaje = mensaje)

######################    
####### AMBOS ########
######################

@viaje_bp.route('/detalle/<idViaje>', methods=['GET', 'POST'])
@login_required
def VerViaje(idViaje):
    try:
        viaje = model.Viaje.query.get(idViaje)
        if not viaje:
            raise Exception("No existe ese viaje")

        idUsuario = current_user.get_id()
        es_pasajero = fsov.usuario_solicito_viaje(idUsuario,viaje.id)
        coordenadas_y_distancia = fpuv.obtener_coordenadas_y_distancia(viaje.ubicacion.direccion_inicial, viaje.ubicacion.direccion_final)
        _, _, _, _, distancia, duracion = coordenadas_y_distancia

        if es_pasajero: 
            return render_template('ver_viaje.html', viaje=viaje, solicitud="Enviada", fechaInicio = viaje.fecha_inicio, distancia = distancia, duracion = duracion)
        else:
            return render_template('ver_viaje.html', viaje=viaje, solicitud="Libre", fechaInicio = viaje.fecha_inicio, distancia = distancia, duracion = duracion)

    except Exception as e:
        mensaje = str(e) 
        return render_template('ver_viaje.html', fechaInicio = viaje.fecha_inicio)

@viaje_bp.route('/ubicacion/<idUsuario>', methods=['GET', 'POST'])
def VerUbicacion(idUsuario):

Viaje/templates/_formhelpers.html
{% macro render_field(field) %}
    <dd>{{ field(**kwargs)|safe }}
      {% if field.errors %}
        <ul class=errors>
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    </dd>
{% endmacro %}

Viaje/templates/buscar_viaje.html
{% extends 'layout.html' %}
{% block banner %}
<!-- Banner -->
<section id="banner" style = "padding-top: 20px;">
    <div class="content">
        <header>
            <h1>Encuentra un viaje hacia tu destino.</h1>
        </header>
        {% if resultado %}
            <a> {{resultado}} </a>
        {% endif%}    
        {% if form %}
            <form method="post" action="{{url_for('viaje_bp.BuscarViaje')}}">
            {{ form.hidden_tag() }}
            <div class="row gtr-uniform">
                <div class="col-6 col-12-xsmall">
                    <h5>Origen</h5>
                    {{ form.origen(type="text",  id="origen", onclick='autocompletar("origen")', placeholder="Origen") }}
                    <div>
                        {% for error in form.origen.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                </div>
                <div class="col-6 col-12-xsmall">
                    <h5>Destino</h5>
                    {{ form.destino(type="text",  id="destino", onclick='autocompletar("destino")', placeholder="Destino") }}
                    <div>
                        {% for error in form.destino.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                </div>
                <div class="col-6 col-12-xsmall">
                    <h5>Fecha</h5>
                    {{ form.fecha_inicio(type="date",  id="fecha_inicio", value="", placeholder="Fecha") }}
                    <div>
                        {% for error in form.fecha_inicio.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                </div>
                <div class="col-6 col-12-xsmall">
                    <h5>Horario</h5>
                    {{ form.hora_inicio(type="time",  id="hora_inicio", value="", placeholder="Horario") }}
                    <div>
                        {% for error in form.hora_inicio.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                </div>
                <!-- Break -->
                <div class="col-12">
                    <ul class="actions">
                        <li>{{ form.submit(type="submit", value="Buscar Viaje") }}</li>
                    </ul>
                </div>
            </div>
        </form>
        {% endif %}
    </div>
    <img src="{{url_for('static', filename = 'images/logo.png')}}" alt="" />
</section>
{% endblock %}
{% block section %}
<!-- Section -->
<section>
    <header class="major">
        <h2>¿Compartir coche? Por qué no...</h2>
    </header>
    <div class="features">
        <article>
            <span class="icon solid fa-sack-dollar"></span>
            <div class="content">
                <h3>Ahorrás</h3>
                <p>Permite ahorrar grandes cantidades de combustible, costes de los peajes o tasas de parking tanto a pasajeros como a conductores, ya que los gastos se dividen entre todos los viajeros.</p>
            </div>
        </article>
        <article>
            <span class="icon solid fa-earth-americas"></span>
            <div class="content">
                <h3>Cuidas el planeta</h3>
                <p>Disminuye las emisiones de CO2 al reducir el número de coches en circulación, sobre todo en grandes ciudades donde las emisiones de dióxido de carbono por parte de los vehículos son preocupantes.</p>
            </div>
        </article>
        <article>
            <span class="icon solid fa-users"></span>
            <div class="content">
                <h3>Socializás</h3>
                <p>Permite crear o afianzar relaciones sociales entre pasajeros y conductores.</p>
            </div>
        </article>
        <article>
            <span class="icon solid fa-car-burst"></span>
            <div class="content">
                <h3>y muchas cosas mas...</h3>
                <p>Hay menos coches en la carretera, por lo que disminuye el tráfico y se reduce el número de accidentes.</p>
            </div>
        </article>
    </div>
</section>

{% if viajes %}
    <!-- Section -->
    <section>
        <header class="major">
            <h2>Últimos viajes agregados.</h2>
        </header>
        <div class="posts">
            {% for viaje in viajes %}
                <article>
                    <a href="{{url_for('viaje_bp.VerViaje',idViaje=viaje.id)}}" class="image">
                        <div class="map-container" style="height: 200px;"
                        data-map-id = "{{viaje.id}}"
                        data-lat-inicial="{{ viaje.ubicacion.latitud_inicial }}"
                        data-lng-inicial="{{ viaje.ubicacion.longitud_inicial }}"
                        data-lat-final="{{ viaje.ubicacion.latitud_final }}"
                        data-lng-final="{{ viaje.ubicacion.longitud_final }}">
                    </div>
                    </a>
                    <h3 style="margin-bottom: 0px;">
                        <a class="fas fa-map-marker-alt" style="margin-right: 10px;"></a>
                        {{viaje.ubicacion.direccion_inicial}}
                    </h3>
                    <h3 style="margin-bottom: 0px;">
                        <a class="fas fa-chevron-down fa-xs"></a>
                    </h3>
                    <h3>
                        <a class="fas fa-map-marker-alt" style="margin-right: 10px;"></a>
                        {{viaje.ubicacion.direccion_final}}
                    </h3>
                    <div>
                        <ul class="icons" style="display: inline;">
                            <li><a class="icon solid fa-calendar-day"></a></li>
                        </ul>
                        <p style="display: inline;margin-bottom: 0px;">Fecha de salida: {{formato_fecha(viaje.fecha_inicio)}}</p>
                    </div>
                    <div>
                        <ul class="icons" style="display: inline;">
                            <li><a class="icon solid fa-clock"></a></li>
                        </ul>
                        <p style="display: inline;margin-bottom: 0px;">Horario de salida: {{formato_hora(viaje.fecha_inicio)}}</p>
                    </div>
                    <div style="margin-bottom: 20px;">
                        <ul class="icons" style="display: inline;">
                            <li><a class="icon solid fa-chair"></a></li>
                        </ul>
                        <p style="display: inline;"> Asientos disponibles: {{viaje.asientos_disponibles}}</p>
                    </div>
                    
                    <ul class="actions">
                        <li><a href="{{url_for('viaje_bp.VerViaje',idViaje=viaje.id)}}" class="button">Ver</a></li>
                    </ul>
                </article>
            {% endfor %}
        </div>
    </section>
{% endif %}  
{% endblock %}

Viaje/templates/grupo_de_viaje.html
{% extends 'layout.html' %}
{% block section %}
<section style = "padding-top: 20px;">
    <header class="major">
        <h2>Grupo de viaje</h2>
    </header>
    {% if viaje %}
        <div class="features">
            <article>
                <span class="icon solid fa-car"></span>
                <div class="content">
                    <h3> 
                        <a href="{{url_for('usuario_bp.PerfilUsuario', idUsuario = viaje.conductor.id_usuario)}}">
                            {{viaje.conductor.usuario.nombre}} {{viaje.conductor.usuario.apellido}}
                        </a>
                    </h3>
                    <h5> Conductor </h5>
                    <p> E-mail: {{viaje.conductor.usuario.email|default("N/A") }} 
                        <BR>
                        Teléfono: {{viaje.conductor.usuario.telefono|default("N/A") }} 
                    </p>
                </div>
            </article>
            {% for pasajero in pasajeros %}
                <article>
                    <span class="icon solid fa-user-check"></span>
                    <div class="content">
                        <h3>
                            <a href="{{url_for('usuario_bp.PerfilUsuario', idUsuario = pasajero.usuario.id)}}"> 
                                {{pasajero.usuario.nombre}} {{pasajero.usuario.apellido}} 
                            </a>
                        </h3>
                        <h5> Pasajero </h5>
                        <p> E-mail: {{pasajero.usuario.email|default("N/A") }} 
                            <BR>
                            Teléfono: {{pasajero.usuario.telefono|default("N/A") }} 
                        </p>
                    </div>
                </article>
            {% endfor %}
        </div>
        {% if viaje.conductor.id_usuario == current_user.id %}
            <h2>Pasajeros</h2>
            <div class="row">
                <div class="col-6 col-12-medium">
                    <ul class="actions stacked">
                        <li>
                            <a href="{{url_for('viaje_bp.VerPasajeros', idViaje = viaje.id, idEstado = 2)}}" class="button fit">Pendientes</a>
                        </li>
                    </ul>
                </div>
                <div class="col-6 col-12-medium">
                    <ul class="actions stacked">
                        <li>
                            <a href="{{url_for('viaje_bp.VerPasajeros', idViaje = viaje.id, idEstado = 3)}}" class="button fit">Rechazados</a>
                        </li>
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endif %}
</section>
{% endblock %}

Viaje/templates/pasajeros_viaje.html
{% extends 'layout.html' %}
{% block section %}
<section style = "padding-top: 20px;">
    <header class="major">
        <h2>Pasajeros</h2>
    </header>
    {% if viaje %}
        
        <div class="features">
            {% for pasajero in pasajeros %}
                {% set estado = pasajero.estado.descripcion %}
                {% set icono = '' %}
                {% set mensaje = '' %}
                {% set acciones_html = '' %}
                
                {% if estado == "Pendiente" %}
                    {% set icono = 'fa-user-clock' %}
                    {% set mensaje = 'Pendiente desde:' %}
                    {% set acciones_html %}
                        <div>
                            <ul class="actions">
                                <li><a href="{{ url_for('viaje_bp.AceptarPasajero', idPasajero=pasajero.id) }}" class="button">Confirmar</a></li>
                                <li><a href="{{ url_for('viaje_bp.RechazarPasajero', idPasajero=pasajero.id) }}" class="button primary">Rechazar</a></li>
                            </ul>
                        </div>
                    {% endset %}
                {% elif estado == "Rechazado" %}
                    {% set icono = 'fa-user-xmark' %}
                    {% set mensaje = 'Fecha rechazo:' %}
                {% elif estado == "Cancelado" %}
                    {% set icono = 'fa-user-minus' %}
                    {% set mensaje = 'Fecha cancelación:' %}
                {% endif %}
                <article>
                    <span class="icon solid {{ icono }}"></span>
                    <div class="content">
                        <h3>
                            <a href="{{url_for('usuario_bp.PerfilUsuario', idUsuario = pasajero.usuario.id)}}"> 
                                {{pasajero.usuario.nombre}} {{pasajero.usuario.apellido}} 
                            </a>
                        </h3>
                        <p> {{ mensaje }} {{ formato_fecha_corta(pasajero.fecha_actualizacion) }}
                        </p>
                        {% if acciones_html %}
                            {{ acciones_html|safe }}
                        {% endif %}
                    </div>
                </article>
            {% endfor %}
        </div>
        {% if not pasajeros %}
            <h4> No se encontraron pasajeros. </h4>
        {% endif %}
    {% endif %}
</section>
{% endblock %}