Usuario/routes.py
from flask import Blueprint, render_template, redirect,url_for,flash
from flask_login import login_user,logout_user,login_required,current_user
from datetime import datetime, timedelta
from authentication import auth
from sqlalchemy.exc import SQLAlchemyError
from app import db
import models as model
import Usuario.forms as formulario
import Usuario.functions.f_perfil as fper
import Usuario.functions.f_editarPerfil as fedp
import Usuario.functions.f_AccionesUsuario as facu
import Viaje.functions.f_AccionesConductor as vfac

usuario_bp = Blueprint('usuario_bp', __name__, url_prefix='/usuario', template_folder='templates', static_folder='static')


@usuario_bp.route('/registro', methods=['GET', 'POST'])
def Registro():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))
    
    form = formulario.RegistroUsuario()

    if form.validate_on_submit():

        nombre= form.nombreUsuario.data
        apellido = form.apellidoUsuario.data
        email = form.email.data.strip()
        telefono = form.telefono.data
        fecha_nacimiento = form.fecha_nacimiento.data
        passw = form.password.data

        usuario_email = model.Usuario.find_by_email(email)
        usuario_telefono = model.Usuario.find_by_telefono(telefono)

        if usuario_email:
            flash("El email especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        elif usuario_telefono:
            flash("El número de teléfono especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        else:
            try:
                nuevoUsuario_firebase = auth.create_user_with_email_and_password(email, passw)
                nuevoUsuario = model.Usuario(
                    nombre=nombre,
                    apellido=apellido,
                    email=email,
                    contrasenia=nuevoUsuario_firebase['idToken'],
                    telefono=telefono,
                    fecha_nacimiento=fecha_nacimiento,
                    fecha_actualizacion=datetime.now(),
                    fecha_creacion= datetime.now(),
                    id_tipo_usuario=1,
                    id_estado_usuario=1
                )
                model.Usuario.save_to_db(nuevoUsuario)
                if model.Usuario.query.get(nuevoUsuario.id):
                    flash("Usuario creado exitosamente, complete sus credenciales para ingresar.")
                    return redirect(url_for('usuario_bp.Login'))
                else:
                    auth.delete_user_account(nuevoUsuario_firebase['idToken'])
                    flash("Hubo un error al crear la cuenta, vuelve a intentarlo más tarde.")
                    return redirect(url_for('usuario_bp.Registro'))
            except:
                flash('Hubo un error con tu cuenta, revisa nuevamente los datos ingresados.')
                return redirect(url_for('usuario_bp.Registro'))
    return render_template('registro.html', form=form)

@usuario_bp.route('/login', methods=['GET', 'POST'])
def Login():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.Login()

    if form.validate_on_submit():

        passw = form.contrasenia.data
        email = form.nombreUsuario.data.strip()
        
        try:
            usuario = model.Usuario.find_by_email(email)

            if usuario:
                inicio = auth.sign_in_with_email_and_password(email, passw)
                if inicio:
                    login_user(usuario)
                    return redirect(url_for('viaje_bp.BuscarViaje'))
                else: 
                    flash("La contraseña ingresada es incorrecta")
                    return redirect(url_for('usuario_bp.Login'))
        except:
            print("exception")
            flash("El usuario ingresado es incorrecto")
            return redirect(url_for('usuario_bp.Login'))
    return render_template('login.html', form=form)

@usuario_bp.route('/reset/contrasenia', methods=['GET', 'POST'])
def ResetearContrasenia():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.ReseteoContrasenia()

    if form.validate_on_submit():
        email = form.emailUsuario.data.strip()
        try:
            auth.send_password_reset_email(email)
            flash('Te enviamos un email a la cuenta de correo para que puedas resetear tu contraseña.')
            return redirect(url_for('usuario_bp.Login'))
        except:
            flash('El correo ingresado no pertenece a una cuenta existente.')
            return redirect(url_for('usuario_bp.ResetearContrasenia'))
    return render_template('reseteoContrasenia.html', form=form)

@usuario_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def Logout():
    logout_user()
    return redirect(url_for('usuario_bp.Login'))


@usuario_bp.route('/perfil', methods=['GET', 'POST'])
@login_required
def Perfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)

@usuario_bp.route('/perfil/<idUsuario>', methods=['GET', 'POST'])
@login_required
def PerfilUsuario(idUsuario):

    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)


@usuario_bp.route('/perfil/editar', methods=['GET', 'POST'])
@login_required
def EditarPerfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)
    print(usuario)
    form = formulario.EditarPerfil()
    
    try:
        if form.validate_on_submit():
            telefono = model.Usuario.query.filter(model.Usuario.telefono == form.telefono.data,
                                                  model.Usuario.id != idUsuario).all()
            if telefono:
                flash("El número de teléfono especificado ya esta en uso.")
                return redirect(url_for('usuario_bp.EditarPerfil'))

            fedp.actualizar_usuario_con_formulario(usuario, form)
            db.session.commit()
            flash('Perfil editado con éxito')
            return redirect(url_for('usuario_bp.Perfil'))
        else:
            fedp.cargar_datos_del_usuario_en_formulario(form, usuario)
            return render_template('editar_perfil.html', form=form, usuario = usuario)
    except SQLAlchemyError as e:
        print('Error al editar el perfil:', str(e))
        return redirect(url_for('usuario_bp.EditarPerfil'))
    

@usuario_bp.route('/perfil/eliminar', methods=['GET', 'POST'])
@login_required
def EliminarCuenta():
    return True

Viaje/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, session
import models as model
from flask_login import login_required,current_user
from datetime import datetime, timedelta
from sqlalchemy.exc import SQLAlchemyError
import routes as r
import Viaje.forms as formulario
from app import maps, db

import Viaje.functions.f_EditarViaje as fedv
import Viaje.functions.f_EliminarViaje as felv
import Viaje.functions.f_PublicarViaje as fpuv
import Viaje.functions.f_SolicitudViaje as fsov
import Viaje.functions.f_AccionesConductor as facc
import Viaje.functions.f_BuscarViaje as fbuv
import Viaje.functions.f_IniciarViaje as finv

viaje_bp = Blueprint('viaje_bp', __name__, url_prefix='/viaje', template_folder='templates', static_folder='static')
 


######################    
##### CONDUCTOR ######
######################

@viaje_bp.route('/publicar', methods=['GET', 'POST'])
@login_required
def PublicarViaje():
    try:
        idUsuario = current_user.get_id()
        conductor = model.Conductor.query.filter_by(id_usuario=idUsuario).all()
        form = formulario.NuevoViaje()

        # Obtener vehículos activos directamente desde Conductor
        vehiculos_activos = (
            model.Conductor.query
            .join(model.Vehiculo)
            .filter(
                model.Conductor.id_usuario == idUsuario,
                model.Vehiculo.id_estado_vehiculo == 1
            )
            .all()
        )

        # Asignar las opciones al campo de selección
        form.vehiculo.choices = [(0, "Vehículo")] + [(c.id, c.vehiculo.patente) for c in vehiculos_activos]


        if form.validate_on_submit():
            fecha_inicial = datetime.combine(form.fecha_inicio.data, form.hora_inicio.data)
            if not fpuv.mayorOigualEdad(fecha_inicial):
                flash('Fecha de inicio del viaje errónea.')
                return redirect(url_for('viaje_bp.PublicarViaje'))
            vehiculo, origen, destino, cantidad_asientos, fecha_inicio, hora_inicio, equipaje, mascota, alimentos = fpuv.obtener_datos_del_formulario(form)
            coordenadas_y_distancia = fpuv.obtener_coordenadas_y_distancia(origen, destino)

            if coordenadas_y_distancia:
                latitud_origen, longitud_origen, latitud_destino, longitud_destino, distancia, duracion = coordenadas_y_distancia

                fpuv.guardar_datos_en_la_base_de_datos(
                    vehiculo, origen, destino, cantidad_asientos, fecha_inicio, hora_inicio,
                    latitud_origen, longitud_origen, latitud_destino, longitud_destino, distancia, duracion,
                    equipaje, mascota, alimentos
                )

                flash('Viaje publicado con éxito', 'success')
                return redirect(url_for('viaje_bp.BuscarViaje'))
            else:
                flash('Hubo un error al obtener detalles de ubicación.', 'error')
        else:
            return render_template('publicar_viaje.html', form=form)
    except Exception as e:
        print(f"Se produjo una excepción: {e}")
        flash('No se pudo publicar el viaje. Inténtalo de nuevo más tarde.')
        return render_template('publicar_viaje.html', form=form)

@viaje_bp.route('/editar/<idViaje>', methods=['GET', 'POST'])
@login_required
def EditarViaje(idViaje):
    viaje = model.Viaje.query.get(idViaje)
    
    if not viaje:
        return fedv.redireccionar_y_mostrar_error('Viaje no encontrado', 'error', 'viaje_bp.ViajesPublicados')
    
    if not fedv.tiene_permiso_para_editar(viaje):
        return fedv.redireccionar_y_mostrar_error('No tienes permiso para editar este viaje', 'error', 'viaje_bp.ViajesPublicados')

    form = fedv.inicializar_formulario(viaje)

    try:
        if form.validate_on_submit():
            fedv.actualizar_viaje_con_formulario(viaje, form)
            db.session.commit()
            flash('Viaje editado con éxito', 'success')
            return redirect(url_for('viaje_bp.VerViaje', idViaje=idViaje))
        else:
            fedv.cargar_datos_del_viaje_en_formulario(form, viaje)
            return render_template('editar_viaje.html', form=form, viaje=viaje)
    except SQLAlchemyError as e:
        flash('Error al editar el viaje', 'error')
        print('Error al editar el viaje:', str(e))
        return redirect(url_for('viaje_bp.ViajesPublicados'))

@viaje_bp.route('/eliminar/<idViaje>', methods=['GET', 'POST'])
@login_required
def EliminarViaje(idViaje):
    viaje = model.Viaje.query.get(idViaje)

    if not viaje:
        return fedv.redireccionar_y_mostrar_error('Viaje no encontrado', 'error', 'viaje_bp.BuscarViaje')

    if not felv.tiene_permiso_para_eliminar(viaje):
        return fedv.redireccionar_y_mostrar_error('No tienes permiso para cancelar este viaje', 'error', 'viaje_bp.BuscarViaje')

    felv.eliminar_viaje(viaje)

    return redirect(url_for('viaje_bp.BuscarViaje'))

@viaje_bp.route('/publicados', methods=['GET', 'POST'])
@login_required
def ViajesPublicados():
    try:
        idUsuario = current_user.get_id()
        # Busco viajes publicados por ese usuario, es decir siendo conductor.
        conductores = model.Conductor.query.filter_by(id_usuario=idUsuario).all()

        viajes_por_conductor = []

        for conductor in conductores:
            viajes = model.Viaje.query.filter_by(id_conductor=conductor.id, id_estado_viaje = 3).order_by(model.Viaje.id.desc()).all()
            viajes_por_conductor.extend(viajes)

        if not viajes_por_conductor:
            raise Exception("No se encontraron viajes correspondientes al conductor.")

        return render_template('viajes_publicados.html', viajes=viajes_por_conductor)
    except Exception as e:
        mensaje = "Usted aún no ha publicado ningún viaje."
        return render_template('viajes_publicados.html', mensaje = mensaje)

@viaje_bp.route('/cancelados', methods=['GET', 'POST'])
@login_required
def ViajesCancelados():
    try:
        idUsuario = current_user.get_id()
        # Busco viajes de ese usuario, es decir siendo conductor.
        conductores = model.Conductor.query.filter_by(id_usuario=idUsuario).all()

        viajes_por_conductor = []

        for conductor in conductores:
            viajes = model.Viaje.query.filter_by(id_conductor=conductor.id, id_estado_viaje = 4).all()
            viajes_por_conductor.extend(viajes)

        if not viajes_por_conductor:
            raise Exception("No se encontraron viajes correspondientes al conductor.")

        return render_template('viajes_cancelados.html', viajes=viajes_por_conductor)
    except Exception as e:
        mensaje = "Usted aún no ha cancelado ningún viaje."
        return render_template('viajes_cancelados.html', mensaje = mensaje)

@viaje_bp.route('pasajero/<idPasajero>/confirmar', methods=['GET', 'POST'])
@login_required
def AceptarPasajero(idPasajero):
    if facc.modificar_estado_pasajero(idPasajero, 'Confirmado'):
        pasajero = model.Pasajero.query.get(idPasajero)
        asientosActuales = pasajero.viaje.asientos_disponibles
        pasajero.viaje.asientos_disponibles = asientosActuales - 1
        db.session.commit()
    return redirect(url_for('viaje_bp.VerViaje', idViaje=pasajero.id_viaje))

@viaje_bp.route('pasajero/<idPasajero>/rechazar', methods=['GET', 'POST'])
@login_required
def RechazarPasajero(idPasajero):
    pasajero = model.Pasajero.query.get(idPasajero)
    if facc.modificar_estado_pasajero(idPasajero, 'Rechazado'):
        return redirect(url_for('viaje_bp.VerViaje', idViaje=pasajero.id_viaje))

@viaje_bp.route('/<idViaje>/pasajeros/<idEstado>', methods=['GET', 'POST'])
@login_required
def VerPasajeros(idViaje, idEstado):
    viaje = model.Viaje.query.get(idViaje)
    #Estado 2 = Pendiente
    #Estado 3 = Rechazado
    #Estado 4 = Cancelado
    pasajeros = fsov.pasajeros_viaje(idViaje, idEstado)

    return render_template('pasajeros_viaje.html', pasajeros = pasajeros, viaje = viaje)

@viaje_bp.route('/solicitudes/recibidas', methods=['GET', 'POST'])
@login_required
def SolicitudesRecibidas():
    idUsuario = current_user.get_id()
    viajes_conductor = facc.viajes_pendientes_como_conductor(idUsuario)

    solicitudes = []
        
    for viaje in viajes_conductor:
        pasajero_pendiente = model.Pasajero.query.filter_by(id_viaje = viaje.id, id_estado_pasajero = 2).first()
        if pasajero_pendiente:
            # Agrega el viaje que tiene pasajeros pendientes de confirmación o rechazo
            solicitudes.append(pasajero_pendiente.viaje)
    if solicitudes:     
        return render_template('solicitudes_recibidas.html', solicitudes = solicitudes)
    else:
        mensaje = 'Usted no ha recibido solicitudes'
        return render_template('solicitudes_recibidas.html', mensaje = mensaje)

######################    
####### AMBOS ########
######################

@viaje_bp.route('/detalle/<idViaje>', methods=['GET', 'POST'])
@login_required
def VerViaje(idViaje):
    try:
        viaje = model.Viaje.query.get(idViaje)
        if not viaje:
            raise Exception("No existe ese viaje")

        idUsuario = current_user.get_id()
        es_pasajero = fsov.usuario_solicito_viaje(idUsuario,viaje.id)
        coordenadas_y_distancia = fpuv.obtener_coordenadas_y_distancia(viaje.ubicacion.direccion_inicial, viaje.ubicacion.direccion_final)
        _, _, _, _, distancia, duracion = coordenadas_y_distancia

        if es_pasajero: 
            return render_template('ver_viaje.html', viaje=viaje, solicitud="Enviada", fechaInicio = viaje.fecha_inicio, distancia = distancia, duracion = duracion)
        else:
            return render_template('ver_viaje.html', viaje=viaje, solicitud="Libre", fechaInicio = viaje.fecha_inicio, distancia = distancia, duracion = duracion)

    except Exception as e:
        mensaje = str(e) 
        return render_template('ver_viaje.html', fechaInicio = viaje.fecha_inicio)

@viaje_bp.route('/ubicacion/<idUsuario>', methods=['GET', 'POST'])
def VerUbicacion(idUsuario):

templates/layout.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>LlevAPPme</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{url_for('static', filename = 'assets/css/main.css')}}" />
		<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">
				<!-- Main -->
					<div id="main">
						<div class="inner">
							<!-- Header -->
							<header id="header">
								<a href="{{url_for('viaje_bp.BuscarViaje')}}" class="logo"><strong>LLEVAPPME</strong></a>
								{% if viaje_en_curso(current_user.id) %}
									<ul id= "idViaje" data-id-viaje= "{{viaje_en_curso(current_user.id)}}" class="icons">
										{% if session.ubicacion_activada|default(False) %}
											<li><a style="color: rgba(3, 177, 61, 0.493)"><span>Ubicación activada</span></a></li>
											<li><a href="{{url_for('viaje_bp.DesactivarUbicacion')}}" style="color: rgba(3, 177, 61, 0.493)" class="fa-solid fa-toggle-on"><span class="label"></span></a></li>
											<li><a href="{{url_for('viaje_bp.VerUbicacion', idUsuario = current_user.id)}}" style="color: rgba(3, 177, 61, 0.493)" class="fa-solid fa-share"><span class="label"></span></a></li>
										{% else %}
											<li><a style="color: rgba(177, 3, 3, 0.493)"><span>Ubicación desactivada</span></a></li>
											<li><a href="{{url_for('viaje_bp.ActivarUbicacion')}}" style="color: rgba(177, 3, 3, 0.493)" class="fa-solid fa-toggle-off"><span class="label"></span></a></li>
										{% endif %}
									</ul>
								{% endif %}
							</header>
							
							<!-- Flash messages -->
							{% with messages = get_flashed_messages() %}
								{% if messages %}
									<ul class=flashes>
									{% for message in messages %}
										<div id= "alerta" class="box" style="background-color: rgb(201, 192, 236);margin-top: 25px;margin-bottom: 0px;">
											<h5 style="margin-bottom: 0px;">
												<a href='' onclick="ocultarAlerta()" class="icon solid fa-xmark"></a>
												&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}
											</h5>
										</div>
									{% endfor %}
									</ul>
								{% endif %}
							{% endwith %}
							
							<!-- Banner -->
							{% block banner %}   
							{% endblock %}

							<!-- Section -->
							{% block section %}   
							{% endblock %}
								
						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Menu -->
								<nav id="menu" style="padding-bottom: 10px;margin-bottom: 20px;">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="{{url_for('viaje_bp.BuscarViaje')}}">Inicio</a></li>
										{% if modo_conductor() %}
											<li><a href="{{url_for('viaje_bp.PublicarViaje')}}">Publicar Viaje</a></li>
										{% endif %}
										<li>
											<span class="opener">Mis viajes</span>
											<ul>
												{% if viaje_en_curso(current_user.id) %}
													<li><a href="{{url_for('viaje_bp.ViajeEnCurso')}}">Viaje en curso</a></li>
												{% endif %}
												<li><a href="{{url_for('viaje_bp.ViajesFinalizados')}}">Viajes Finalizados</a></li>
												{% if modo_conductor() %}
													<li><a href="{{url_for('viaje_bp.ViajesPublicados')}}">Viajes Publicados</a></li>
													<li><a href="{{url_for('viaje_bp.ViajesCancelados')}}">Viajes Cancelados</a></li>
												{% endif %}
											</ul>
										</li>
										<li>
											<span class="opener">Mis Solicitudes</span>
											<ul>
												<li><a href="{{url_for('viaje_bp.SolicitudesEnviadas')}}">Solicitudes enviadas</a></li>
												{% if modo_conductor() %}
													<li><a href="{{url_for('viaje_bp.SolicitudesRecibidas')}}">Solicitudes recibidas</a></li>
												{% endif %}
											</ul>
										</li>
										{% if modo_conductor() %}
											<li>
												<span class="opener">Mis Vehiculos</span>
												<ul>
													<li><a href="{{url_for('vehiculo_bp.Vehiculo')}}">Nuevo Vehiculo</a></li>
													<li><a href="{{url_for('vehiculo_bp.ListadoVehiculos')}}">Mis Vehiculos</a></li>
												</ul>
											</li>
										{% endif %}
										<li><a href="{{url_for('usuario_bp.Perfil')}}">Perfil</a></li>
										<li><a href="{{url_for('usuario_bp.Logout')}}">Salir</a></li>
									</ul>									
								</nav>
								{% if not modo_conductor() %}
								<section>
									<header class="major">
										<h2>Conductor</h2>
									</header>
									<p>Conviertete en un conductor en un simple paso, registra el vehículo con el que vas a conducir y listo.</p>
									<a href="{{url_for('vehiculo_bp.Vehiculo')}}" class="button fit">¡Vamos!</a>
								</section>
								{% endif %}
							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">
										&copy; LlevAPPme. All rights reserved. 
										<br/> UTN - FRD - Proyecto final
										<br/> Ingeniería en Sistemas de Información.
										<br/> Timoteo, Jonathan, Evelyn.
									</p>
								</footer>

						</div>
					</div>

			</div>

			<script>
				var ubicacionActivadaValue = "{{ session.ubicacion_activada|default(False)|lower }}";
			</script>
			<script>
				let ubicacionActivada = ubicacionActivadaValue === "true";
				let intervaloGeolocalizacion;
				
				// Función para activar la ubicación automáticamente si la sesión está en True
				function activarUbicacionAutomaticamente() {
					if (ubicacionActivada) {
						obtenerYGuardarUbicacion(); // Comenzar la geolocalización
					}
				}
				
				// Función para obtener y guardar la ubicación
				function obtenerYGuardarUbicacion() {
				if (!ubicacionActivada) {
					console.log("La ubicación no está activada.");
					clearInterval(intervaloGeolocalizacion); // Detiene la geolocalización
					return;
				}
				
				if ("geolocation" in navigator) {
					navigator.geolocation.getCurrentPosition(function(position) {
					const latitud = position.coords.latitude;
					const longitud = position.coords.longitude;
				
					// Enviar los datos al servidor
					enviarUbicacionAlServidor(latitud, longitud);
					});
				} else {
					console.log("El navegador no admite la geolocalización.");
				}
				
				// Programar la próxima actualización después de 5 segundos
				setTimeout(obtenerYGuardarUbicacion, 5000);
				}
				
				// Obtener id de viaje en cuestion
				function obtenerIdViaje() {
				  const elementoConViaje = document.getElementById("idViaje");
				  const idViaje = elementoConViaje.getAttribute("data-id-viaje");
				  return idViaje;
				}
				
				// Función para enviar la ubicación al servidor
				function enviarUbicacionAlServidor(latitud, longitud) {
				fetch("/viaje/guardar/ubicacion", {
					method: "POST",
					headers: {
					"Content-Type": "application/json",
					},
					body: JSON.stringify({ idViaje: obtenerIdViaje(), latitud, longitud }),
				})
					.then((response) => {
					if (response.ok) {
						console.log("Ubicación guardada con éxito en el servidor.");
					} else {
						console.error("Error al guardar la ubicación en el servidor.");
					}
					})
					.catch((error) => {
					console.error("Error al realizar la solicitud al servidor: " + error);
					});
				}
				
				function ocultarAlerta() {
					const alerta = document.getElementById("alerta");
					if (alerta.style.display === 'block') {
						// Si está oculto, mostrarlo
						alerta.style.display = 'none';
					}
				}

				// Llama a la función para activar la ubicación automáticamente al cargar la página
				window.addEventListener('load', activarUbicacionAutomaticamente);
			</script>

		<!-- Scripts -->
			<script src="{{url_for('static', filename = 'assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static', filename = 'assets/js/browser.min.js')}}"></script>
			<script src="{{url_for('static', filename = 'assets/js/breakpoints.min.js')}}"></script>
			<script src="{{url_for('static', filename = 'assets/js/util.js')}}"></script>
			<script src="{{url_for('static', filename = 'assets/js/main.js')}}"></script>
			<script src="{{url_for('static', filename = 'assets/js/googlemaps.js')}}"></script>
			<script src="https://kit.fontawesome.com/228c5469ee.js" crossorigin="anonymous"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBPrNn6olS4yqaOK9v7ppvXnu4kXQ_x_98&libraries=places&callback=initMap&v=weekly&solution_channel=GMP_QB_addressselection_v1_cA" defer></script>
			
			{% block script %}   

			{% endblock %}
			


	</body>
</html>