Vehiculo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField ,PasswordField, SubmitField, IntegerField, SelectField, TextAreaField, RadioField
from wtforms.fields.core import BooleanField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import DataRequired, Length, EqualTo, Email, ValidationError
from wtforms_sqlalchemy.fields import QuerySelectField

import models as model

class CrearVehiculo(FlaskForm):
    patente = StringField('Patente', validators=[DataRequired(), Length(min=6, max=7)])
    cantidad_asientos = IntegerField('Cantidad de asientos', validators=[DataRequired()])
    descripcion = TextAreaField('Descripcion', validators=[DataRequired()])
    submit = SubmitField('Agregar Vehiculo')

Usuario/routes.py
from flask import Blueprint, render_template, redirect,url_for,flash
from flask_login import login_user,logout_user,login_required,current_user
from datetime import datetime, timedelta
from authentication import auth
from sqlalchemy.exc import SQLAlchemyError
from app import db
import models as model
import Usuario.forms as formulario
import Usuario.functions.f_perfil as fper
import Usuario.functions.f_editarPerfil as fedp
import Usuario.functions.f_AccionesUsuario as facu
import Viaje.functions.f_AccionesConductor as vfac

usuario_bp = Blueprint('usuario_bp', __name__, url_prefix='/usuario', template_folder='templates', static_folder='static')


@usuario_bp.route('/registro', methods=['GET', 'POST'])
def Registro():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))
    
    form = formulario.RegistroUsuario()

    if form.validate_on_submit():

        nombre= form.nombreUsuario.data
        apellido = form.apellidoUsuario.data
        email = form.email.data.strip()
        telefono = form.telefono.data
        fecha_nacimiento = form.fecha_nacimiento.data
        passw = form.password.data

        usuario_email = model.Usuario.find_by_email(email)
        usuario_telefono = model.Usuario.find_by_telefono(telefono)

        if usuario_email:
            flash("El email especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        elif usuario_telefono:
            flash("El número de teléfono especificado ya esta en uso.")
            return render_template('registro.html', form=form)
        else:
            try:
                nuevoUsuario_firebase = auth.create_user_with_email_and_password(email, passw)
                nuevoUsuario = model.Usuario(
                    nombre=nombre,
                    apellido=apellido,
                    email=email,
                    contrasenia=nuevoUsuario_firebase['idToken'],
                    telefono=telefono,
                    fecha_nacimiento=fecha_nacimiento,
                    fecha_actualizacion=datetime.now(),
                    fecha_creacion= datetime.now(),
                    id_tipo_usuario=1,
                    id_estado_usuario=1
                )
                model.Usuario.save_to_db(nuevoUsuario)
                if model.Usuario.query.get(nuevoUsuario.id):
                    flash("Usuario creado exitosamente, complete sus credenciales para ingresar.")
                    return redirect(url_for('usuario_bp.Login'))
                else:
                    auth.delete_user_account(nuevoUsuario_firebase['idToken'])
                    flash("Hubo un error al crear la cuenta, vuelve a intentarlo más tarde.")
                    return redirect(url_for('usuario_bp.Registro'))
            except:
                flash('Hubo un error con tu cuenta, revisa nuevamente los datos ingresados.')
                return redirect(url_for('usuario_bp.Registro'))
    return render_template('registro.html', form=form)

@usuario_bp.route('/login', methods=['GET', 'POST'])
def Login():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.Login()

    if form.validate_on_submit():

        passw = form.contrasenia.data
        email = form.nombreUsuario.data.strip()
        
        try:
            usuario = model.Usuario.find_by_email(email)

            if usuario:
                inicio = auth.sign_in_with_email_and_password(email, passw)
                if inicio:
                    login_user(usuario)
                    return redirect(url_for('viaje_bp.BuscarViaje'))
                else: 
                    flash("La contraseña ingresada es incorrecta")
                    return redirect(url_for('usuario_bp.Login'))
        except:
            print("exception")
            flash("El usuario ingresado es incorrecto")
            return redirect(url_for('usuario_bp.Login'))
    return render_template('login.html', form=form)

@usuario_bp.route('/reset/contrasenia', methods=['GET', 'POST'])
def ResetearContrasenia():
    if current_user.is_authenticated:
        return redirect(url_for('viaje_bp.BuscarViaje'))

    form = formulario.ReseteoContrasenia()

    if form.validate_on_submit():
        email = form.emailUsuario.data.strip()
        try:
            auth.send_password_reset_email(email)
            flash('Te enviamos un email a la cuenta de correo para que puedas resetear tu contraseña.')
            return redirect(url_for('usuario_bp.Login'))
        except:
            flash('El correo ingresado no pertenece a una cuenta existente.')
            return redirect(url_for('usuario_bp.ResetearContrasenia'))
    return render_template('reseteoContrasenia.html', form=form)

@usuario_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def Logout():
    logout_user()
    return redirect(url_for('usuario_bp.Login'))


@usuario_bp.route('/perfil', methods=['GET', 'POST'])
@login_required
def Perfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)

@usuario_bp.route('/perfil/<idUsuario>', methods=['GET', 'POST'])
@login_required
def PerfilUsuario(idUsuario):

    usuario = model.Usuario.query.get(idUsuario)

    viajesPasajero = len(model.Pasajero.query.filter_by(id_usuario = idUsuario, id_estado_pasajero = 6).all())
    viajesConductor = len(vfac.viajes_finalizados_como_conductor(idUsuario))

    edad = fper.calcular_edad(usuario.fecha_nacimiento)
    return render_template('perfil.html', edad = edad, viajesPasajero = viajesPasajero, viajesConductor = viajesConductor, usuario = usuario)


@usuario_bp.route('/perfil/editar', methods=['GET', 'POST'])
@login_required
def EditarPerfil():
    idUsuario = current_user.get_id()
    usuario = model.Usuario.query.get(idUsuario)
    print(usuario)
    form = formulario.EditarPerfil()
    
    try:
        if form.validate_on_submit():
            telefono = model.Usuario.query.filter(model.Usuario.telefono == form.telefono.data,
                                                  model.Usuario.id != idUsuario).all()
            if telefono:
                flash("El número de teléfono especificado ya esta en uso.")
                return redirect(url_for('usuario_bp.EditarPerfil'))

            fedp.actualizar_usuario_con_formulario(usuario, form)
            db.session.commit()
            flash('Perfil editado con éxito')
            return redirect(url_for('usuario_bp.Perfil'))
        else:
            fedp.cargar_datos_del_usuario_en_formulario(form, usuario)
            return render_template('editar_perfil.html', form=form, usuario = usuario)
    except SQLAlchemyError as e:
        print('Error al editar el perfil:', str(e))
        return redirect(url_for('usuario_bp.EditarPerfil'))
    

@usuario_bp.route('/perfil/eliminar', methods=['GET', 'POST'])
@login_required
def EliminarCuenta():
    return True

Vehiculo/routes.py
from flask import Blueprint, render_template, redirect,url_for,flash
from flask_login import login_user,logout_user,login_required,current_user
from datetime import datetime, timedelta
import models as model
import Vehiculo.forms as formulario
from app import db

import Vehiculo.functions.f_EliminarVehiculo as felv
import Vehiculo.functions.f_NuevoVehiculo as fnuv
import Usuario.functions.f_AccionesUsuario as faccu

vehiculo_bp = Blueprint('vehiculo_bp', __name__, url_prefix='/vehiculo', template_folder='templates', static_folder='static')


#VIAJE SEGUN ESTADO
@vehiculo_bp.route('/', methods=['GET', 'POST'])
@login_required
def Vehiculo():
    form = formulario.CrearVehiculo()
    if form.validate_on_submit():

        patente = form.patente.data.upper()
        cantidad_asientos = form.cantidad_asientos.data
        descripcion = form.descripcion.data

        vehiculo = fnuv.CrearVehiculo(patente,cantidad_asientos,descripcion)
        
        if vehiculo:
            idUsuario = current_user.get_id()
            fnuv.AltaConductor(idUsuario, vehiculo.id)
            flash('Vehiculo creado con éxito.')    
            return redirect(url_for('viaje_bp.BuscarViaje'))
        
        flash('No se ha podido crear el vehiculo.')
        return redirect(url_for('viaje_bp.BuscarViaje'))
    
    return render_template('vehiculo.html', form = form)

@vehiculo_bp.route('/listado', methods=['GET', 'POST'])
@login_required
def ListadoVehiculos():
    idUsuario = current_user.get_id()
    # Obtener solo los vehículos activos
    vehiculos = (
        db.session.query(model.Vehiculo)
        .join(model.Conductor)
        .filter(
            model.Conductor.id_usuario == idUsuario,
            model.Vehiculo.id_estado_vehiculo == 1
        )
        .all()
    )
    return render_template('listado_vehiculos.html', vehiculos = vehiculos)
    
@vehiculo_bp.route('/eliminar/<idVehiculo>', methods=['GET', 'POST'])
@login_required
def EliminarVehiculo(idVehiculo):

    eliminar = felv.eliminarVehiculo(idVehiculo)
    convertir = faccu.ConvertirEnPasajero(current_user.id)
    if (not convertir) and eliminar:
        flash('Se eliminó el vehiculo del listado de vehiculos.')
        return redirect(url_for('vehiculo_bp.ListadoVehiculos'))
    elif eliminar:
        flash('Se eliminó el vehiculo del listado de vehiculos. Ahora estás en modo pasajero, para volver a ser un conductor, crea un nuevo vehículo')
        return redirect(url_for('viaje_bp.BuscarViaje'))
    else:
        return redirect(url_for('vehiculo_bp.ListadoVehiculos'))

Vehiculo/templates/cedula.html
<html>
	<head>
		<title>LLEVAPPME</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    </head>
	<body>
        <section>
            {% from "_formhelpers.html" import render_field %}
            <form method="post" action="{{url_for('vehiculo_bp.CrearCedula', idVehiculo = 3)}}">
                {{ form.hidden_tag() }}
            <dl>
                {{ render_field(form.numero) }}
                {{ render_field(form.imagen) }}
                {{ render_field(form.fecha_otorgamiento) }}
                {{ render_field(form.fecha_vencimiento) }}
            </dl>
            {{ render_field(form.submit) }}
            </form>
        </section>						

        <a href="{{url_for('usuario_bp.Logout')}}">Salir</a>
	</body>
</html>

Vehiculo/templates/listado_vehiculos.html
{% extends 'layout.html' %}
{% block section %}
<section style = "padding-top: 20px;">
    <!-- Elements -->
    <h2 id="elements">Mis Vehiculos</h2>
        {% if vehiculos %}
            <div class="table-wrapper">
                <table class="alt">
                    <thead>
                        <tr>
                            <th scope="col">Patente</th>
                            <th scope="col">Asientos</th>
                            <th scope="col">Descripción</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for v in vehiculos %}
                            <tr>
                                <td> {{ v.patente }}</td>
                                <td> {{ v.cantidad_asientos }}</td>
                                <td> {{ v.descripcion }}</td>
                                <td> 
                                    <a href="{{url_for('vehiculo_bp.EliminarVehiculo', idVehiculo=v.id)}}">Eliminar vehiculo</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
        {% if mensaje %}
            <a>{{mensaje}}</a>
        {% endif %}
</section>

{% endblock %}

Vehiculo/templates/vehiculo.html
{% extends 'layout.html' %}
{% block section %}
<!-- Section -->
<section style = "padding-top: 20px;">
    <header class="major">
        <h2>Nuevo Vehiculo</h2>
    </header>
    {% if resultado %}
        <a> {{resultado}} </a>
    {% endif%}    
    {% if form %}
        <form method="post" action="{{url_for('vehiculo_bp.Vehiculo')}}">
        {{ form.hidden_tag() }}
        <div class="row gtr-200">
            <div class="col-9 col-12-medium">
                <div class="row gtr-uniform">
                    <div class="col-6 col-12-xsmall">
                        <h5>Patente</h5>
                        {{ form.patente(type="text",  id="patente", value="", placeholder="Patente") }}
                        <div>
                            {% for error in form.patente.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-6 col-12-xsmall">
                        <h5>Asientos disponibles</h5>
                        {{ form.cantidad_asientos(type="tel",  id="cant_asientos", value="", placeholder="Cantidad asientos disponibles") }}
                        <div>
                            {% for error in form.cantidad_asientos.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-12 col-12-xsmall">
                        <h5>Descripción</h5>
                        {{ form.descripcion(type="text",  id="descripcion", value="", placeholder="Describí tu vehiculo. Tipo de vehiculo, modelo, color...") }}
                        <div>
                            {% for error in form.descripcion.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    </div>
                
                    <div class="col-12">
                        <ul class="actions">
                            <li>{{ form.submit(type="submit", value="Crear Vehiculo") }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% endif %}
{% endblock %}